# Generated by Django 4.1.2 on 2022-10-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthform",
            name="user_photo",
            field=models.ImageField(upload_to="uploads/student_images"),
        ),
        migrations.AlterField(
            model_name="healthform",
            name="vaccine_card",
            field=models.ImageField(upload_to="uploads/vaccine_cards"),
        ),
    ]
