# Generated by Django 4.1.2 on 2022-10-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_healthform_user_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flairuser",
            name="username",
        ),
    ]
